/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rdict.h"

#define	MAXWORD	50		/* maximum length of a command or word	*/
#define DICTSIZ 100		/* maximum number of entries in diction.*/
int	nwords = 0;		/* number of words in the dictionary	*/
char	dict[DICTSIZ][MAXWORD+1];/* storage for a dictionary of words	*/

int *
initw_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result = 1;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
insertw_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	strcpy(dict[nwords], argp);
	nwords++;
	result = nwords;

	return &result;
}

int *
deletew_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	int	i;

	for (i=0 ; i<nwords ; i++)
		if (strcmp(argp, dict[i]) == 0) {
			nwords--;
			strcpy(dict[i], dict[nwords]);
			result = 1;
			return &result;
		}
	result = 0;

	return &result;
}

int *
lookupw_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	int	i;

	for (i=0 ; i<nwords ; i++)
		if (strcmp(argp, dict[i]) == 0)
			result = 1; return &result;

	result = 0;

	return &result;
}
