/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rdict.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <signal.h>

int	nwords = 0;		/* number of words in the dictionary	*/
char	dict[DICTSIZ][MAXWORD+1];/* storage for a dictionary of words	*/

int *
initw_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
	nwords = 0;
	result = 1;
	return (&result);
}

int *
insertw_1_svc(char **argp, struct svc_req *rqstp)
{
		static int  result;
	char *word;

	word = *argp;
	strcpy(dict[nwords], word);
	nwords++;
	result = nwords;
	return (&result);
}

int *
deletew_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;
	char *word;
	int i;

	word = *argp;
	for (i=0 ; i<nwords ; i++)
		if (strcmp(word, dict[i]) == 0) {
			nwords--;
			strcpy(dict[i], dict[nwords]);
			result = 1;
			return (&result);
		}
	result = 0;
	return (&result);
}

int *
lookupw_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;
	char *word;
	int i;

	word = *argp;
	for (i=0 ; i<nwords ; i++)
		if (strcmp(word, dict[i]) == 0) {
			result = 1;
			return (&result);
		}
	result = 0;
	return (&result);
}